nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ["%env(CORS_ALLOW_ORIGIN)%"]
        allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
        allow_headers: ["Content-Type", "Authorization", "X-AUTH-TOKEN"]
        expose_headers: ["Link"]
        max_age: 3600
    paths:
        "^/":
            allow_origin:
                - "http://localhost:5173" # Vite (dev)
                - "http://localhost:3000" # Next/Vite alternatif (dev)
                - "https://main-bvxea6i-mvgwmzcr2brk2.fr-3.platformsh.site"
            allow_headers: ["Content-Type", "Authorization", "X-AUTH-TOKEN"]
            allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
            max_age: 3600
