# .platform.app.yaml
name: app
type: php:8.4

runtime:
    extensions:
        - apcu
        - mbstring
        - sodium
        - ctype
        - iconv

disk: 1024

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

# Un seul mount /var suffit (cache, logs, sessions…)
mounts:
    "/var": { source: local, source_path: var }
    "public/uploads":
        source: local
        source_path: "uploads"

# Lier l’app au service MySQL défini dans .platform/services.yaml
relationships:
    database: "database:mysql"

# Variables d’environnement runtime
variables:
    env:
        APP_ENV: "prod"
        APP_DEBUG: "0"

build:
    flavor: none

hooks:
    build: |
        set -e -x
        # Outils Symfony/Cloud OK
        curl -fs https://get.symfony.com/cloud/configurator | bash
        # Installer les dépendances SANS scripts (évite cache:clear en build)
        composer install --no-dev --prefer-dist --no-progress --no-interaction --optimize-autoloader --classmap-authoritative --no-scripts

    deploy: |
        set -e -x
        # Ici la relation DB est injectée -> DATABASE_URL est dispo
        php bin/console cache:clear --no-warmup
        php bin/console doctrine:migrations:migrate --no-interaction
        php bin/console cache:warmup

crons:
    security-check:
        spec: "50 23 * * *"
        cmd: if [ "$PLATFORM_ENVIRONMENT_TYPE" = "production" ]; then croncape COMPOSER_ROOT_VERSION=1.0.0 COMPOSER_AUDIT_ABANDONED=ignore composer audit --no-cache; fi
    clean-expired-sessions:
        spec: "17,47 * * * *"
        cmd: croncape php-session-clean
