services:
    app:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        environment:
            APP_ENV: prod
            APP_DEBUG: "0"
            # ⚠️ POINTE VERS TA DB DE PROD (gérée ou en container)
            DATABASE_URL: "${DATABASE_URL}"
            TRUSTED_PROXIES: "127.0.0.1,172.16.0.0/12"
            TRUSTED_HOSTS: "^api\\.ton-domaine\\.fr$"
        volumes:
            - .:/var/www/app
        depends_on:
            - web

    web:
        image: nginx:1.27-alpine
        depends_on:
            - app
        ports:
            - "80:80" # derrière un proxy TLS ou un LB
        volumes:
            - .:/var/www/app
            - ./.docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf:ro
