services:
    db:
        image: mysql:8.0
        container_name: quaiantiqueback-db-1
        environment:
            MYSQL_DATABASE: quai_antique
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3307:3306"
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -uroot -proot --silent"]
            interval: 5s
            timeout: 3s
            retries: 20
        volumes:
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin:5
        container_name: quaiantiqueback-phpmyadmin-1
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - "8081:80"
        depends_on:
            - db

    app:
        # si tu as un Dockerfile PHP-FPM, sinon remplace par "image: php:8.3-fpm"
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        container_name: quaiantiqueback-app-1
        environment:
            APP_ENV: "prod"
            APP_DEBUG: "0"
            DATABASE_URL: "mysql://symfony:symfony@db:3306/quai_antique?serverVersion=8.0"
        volumes:
            - ./:/var/www/app
        depends_on:
            db:
                condition: service_healthy

    web:
        image: nginx:1.27-alpine
        container_name: quaiantiqueback-web-1
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/app
            - ./.docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app

volumes:
    db_data:
